# version: '3.8'

services:
  postgres:
    image: postgres:17
    command: -p 5433
    container_name: postgres-notes_users
    environment:
      POSTGRES_DB: ${USERS_DB_NAME}
      POSTGRES_USER: ${USERS_DB_USER}
      POSTGRES_PASSWORD: ${USERS_DB_PWD}
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5433 -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_users:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis-notes_users
    ports:
      - "6380:6380"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - redis_data_users:/data
    command: redis-server --port 6380 --appendonly yes --appendfsync everysec
    networks:
      - app-network

  notes-users-service:
    build: .
    container_name: notes_users
    ports:
      - "8002:8002"
    environment:
      APP_MODE: ${USERS_APP_MODE}

      USERS_DB_HOST: postgres
      USERS_DB_PORT: 5433
      USERS_DB_NAME: ${USERS_DB_NAME}
      USERS_DB_USER: ${USERS_DB_USER}
      USERS_DB_PWD: ${USERS_DB_PWD}

      USERS_REDIS_HOST: redis
      USERS_REDIS_PORT: 6380
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    command: ["bash", "-c", "alembic upgrade head && python main.py"]
    restart: always
    networks:
      - app-network

volumes:
  postgres_data_users:
  redis_data_users:

networks:
  app-network:
    external: true
