services:
  postgres:
    image: postgres:17
    command: -p 5434
    container_name: postgres-media
    environment:
      POSTGRES_DB: ${MEDIA_DB_NAME}
      POSTGRES_USER: ${MEDIA_DB_USER}
      POSTGRES_PASSWORD: ${MEDIA_DB_PWD}
    ports:
      - "5434:5434"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5434 -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_media:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network
  
  notes-media-service:
    build: .
    container_name: notes_media
    ports:
      - "8003:8003"
    environment:
      MEDIA_APP_MODE: ${MEDIA_APP_MODE}

      MEDIA_DB_HOST: postgres
      MEDIA_DB_PORT: 5434
      MEDIA_DB_NAME: ${MEDIA_DB_NAME}
      MEDIA_DB_USER: ${MEDIA_DB_USER}
      MEDIA_DB_PWD: ${MEDIA_DB_PWD}
      MEDIA_DB_ECHO: ${MEDIA_DB_ECHO}

      MEDIA_S3_ACCESSKEY: ${MEDIA_S3_ACCESSKEY}
      MEDIA_S3_SECRETKEY: ${MEDIA_S3_SECRETKEY}
      MEDIA_S3_ENDPOINTURL: ${MEDIA_S3_ENDPOINTURL}
      MEDIA_S3_BUCKETNAME: ${MEDIA_S3_BUCKETNAME}
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    command: ["bash", "-c", "service clamav-daemon start && alembic upgrade head && python main.py"]
    networks:
      - app-network

volumes:
  postgres_data_media:

networks:
  app-network:
    external: true
