name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
    
    steps:
    - uses: actions/checkout@v4 # Step 1: Check out the repository code
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5 # Step 2: Set up a specific Python version
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # Optional: Cache dependencies for faster subsequent runs
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest # Install linting and testing libraries
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --strict
        # flake8 . --count --exit-index=1 --max-complexity=10 --max-line-length=127 --statistics
    # - name: Test with pytest
    #   run: |
    #     pytest # Run your project's tests
