# version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres-notes_service
    environment:
      POSTGRES_DB: ${APP__CONFIG__DB__NAME}
      POSTGRES_USER: ${APP__CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${APP__CONFIG__DB__PWD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d default_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

  notes_service:
    build: .
    container_name: notes_service
    ports:
      - "8000:8000"
    environment:
      APP__CONFIG__RUN__MODE: ${APP__CONFIG__RUN__MODE} 

      APP__CONFIG__DB__HOST: postgres
      APP__CONFIG__DB__PORT: ${APP__CONFIG__DB__PORT}
      APP__CONFIG__DB__NAME: ${APP__CONFIG__DB__NAME}
      APP__CONFIG__DB__USER: ${APP__CONFIG__DB__USER}
      APP__CONFIG__DB__PWD: ${APP__CONFIG__DB__PWD}
      APP__CONFIG__DB__ECHO: ${APP__CONFIG__DB__ECHO}

      APP__CONFIG__S3__ACCESS_KEY: ${APP__CONFIG__S3__ACCESS_KEY}
      APP__CONFIG__S3__SECRET_ACCESS_KEY: ${APP__CONFIG__S3__SECRET_ACCESS_KEY}
      APP__CONFIG__S3__ENDPOINT_URL: ${APP__CONFIG__S3__ENDPOINT_URL}
      APP__CONFIG__S3__BUCKET_NAME: ${APP__CONFIG__S3__BUCKET_NAME} 
    depends_on:
      postgres:
        condition: service_healthy
    command: ["bash", "-c", "alembic upgrade head && python main.py"]

volumes:
  postgres_data:
