# version: 3.8

services:
  krakend:
    image: devopsfaith/krakend:2.4.0 
    container_name: krakend-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    networks:
      - app-network
    restart: always

networks: 
  app-network:
    external: true